<?php

namespace AppBundle\Repository;

/**
 * NeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeedRepository extends \Doctrine\ORM\EntityRepository
{
}
